export const SET_STORE_DATA = "SET_STORE_DATA";
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const TOGGLE_OVERLAY = "TOGGLE_OVERLAY";
export const TOGGLE_NAVBAR_MENU_LIST = "TOGGLE_NAVBAR_MENU_LIST";
export const TOGGLE_SHOW_DONATION_MENU = "TOGGLE_SHOW_DONATION_MENU";